### ISSUE TITLE
Remove items with no permission to use

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/maps-collection#25]
In the metadata, remove any items we don't have permission to use. Please save this info as a separate Google sheet.

**Comment by cfokkens** [comment]
No pictures: https://docs.google.com/spreadsheets/d/1nW5zEa0_8Z9iP0r2-9MXfQ46q_-EdOkDJYGu7mOUy8k/edit#gid=0 
The full set: https://docs.google.com/spreadsheets/d/1hnjscC1yolEUOfZDKLqlxCQFQbpdO9p4PYqgjCB0Vsc/edit#gid=0
